In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
Data_One = pd.read_csv("jester-data-1.csv")
No_One = np.array(Data_One['H'])
del Data_One['H']
Data_One = np.array(Data_One)
Data_Two = pd.read_csv("jester-data-2.csv")
No_Two = np.array(Data_Two['H'])
del Data_Two['H']
Data_Two = np.array(Data_Two)
Data_Three = pd.read_csv("jester-data-3.csv")
No_Three = np.array(Data_Three['H'])
del Data_Three['H']
Data_Three = np.array(Data_Three)


In [3]:
Data = np.concatenate((Data_One,Data_Two),axis=0)
Data = np.concatenate((Data,Data_Three),axis=0)
Jokes = np.concatenate((No_One,No_Two),axis=0)
Jokes = np.concatenate((Jokes,No_Three),axis=0)

In [4]:
ls = { "No_Of_Jokes":Jokes, "Ratings":Data }
pickle.dump(ls, open( "Jester_Dataset", "wb" ) )

In [5]:
ls['Ratings']

array([[ -7.82,   8.79,  -9.66, ...,  99.  ,  99.  ,  99.  ],
       [  4.08,  -0.29,   6.36, ...,   0.34,  -4.32,   1.07],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ..., 
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ]])

In [6]:
ls['Ratings'].shape

(73421, 100)

In [7]:
Test_List=[]
Train_List=[]
for _ in range(len(ls['Ratings'])):
    if np.count_nonzero(ls['Ratings'][_]==99.0) <=25:
        Test_List.append(ls['Ratings'][_])
    else:
        Train_List.append(ls['Ratings'][_])
Test_List = np.array(Test_List)
Train_List = np.array(Train_List)

In [8]:
Train_List.shape

(54618, 100)

In [9]:
Test_List[0]

array([ 4.08, -0.29,  6.36,  4.37, -2.38, -9.66, -0.73, -5.34,  8.88,
        9.22,  6.75,  8.64,  4.42,  7.43,  4.56, -0.97,  4.66, -0.68,
        3.3 , -1.21,  0.87,  8.64,  8.35,  9.17,  0.05,  7.57,  4.71,
        0.87, -0.39,  6.99,  6.5 , -0.92,  7.14,  9.03, -1.8 ,  0.73,
        7.09,  3.4 , -0.87,  7.91,  7.82, -3.83,  8.64,  8.98, -4.32,
       -3.2 , -4.9 , -0.92, -1.46,  3.64,  3.16,  9.03,  0.97, -1.31,
       -6.5 , -3.2 ,  8.64, -2.14,  0.1 ,  9.03, -6.7 , -3.35, -9.03,
        4.47,  4.08, -3.83,  8.74,  1.12,  0.78,  7.52, -5.  ,  2.77,
        8.3 ,  7.77,  7.33,  6.21,  7.72,  8.98,  8.64,  8.2 ,  3.93,
        4.85,  4.85,  6.07,  8.98,  4.51, -0.05,  3.69,  4.56,  0.58,
        2.82, -4.95, -0.29,  7.86, -0.19, -2.14,  3.06,  0.34, -4.32,  1.07])

In [10]:
Test_x=[]
Test_y=[]
for _ in range(len(Test_List)):
    Test_x.append(Test_List[_][:70])
    Test_y.append(Test_List[_][70:])
Test_x = np.array(Test_x)
Test_y = np.array(Test_y)

Train_x=[]
Train_y=[]
for _ in range(len(Train_List)):    
    Train_x.append(Train_List[_][:70])
    Train_y.append(Train_List[_][70:])
Train_x = np.array(Train_x)
Train_y = np.array(Train_y)


In [11]:
Test_x[0]

array([ 4.08, -0.29,  6.36,  4.37, -2.38, -9.66, -0.73, -5.34,  8.88,
        9.22,  6.75,  8.64,  4.42,  7.43,  4.56, -0.97,  4.66, -0.68,
        3.3 , -1.21,  0.87,  8.64,  8.35,  9.17,  0.05,  7.57,  4.71,
        0.87, -0.39,  6.99,  6.5 , -0.92,  7.14,  9.03, -1.8 ,  0.73,
        7.09,  3.4 , -0.87,  7.91,  7.82, -3.83,  8.64,  8.98, -4.32,
       -3.2 , -4.9 , -0.92, -1.46,  3.64,  3.16,  9.03,  0.97, -1.31,
       -6.5 , -3.2 ,  8.64, -2.14,  0.1 ,  9.03, -6.7 , -3.35, -9.03,
        4.47,  4.08, -3.83,  8.74,  1.12,  0.78,  7.52])

In [12]:
Test_y[0]

array([-5.  ,  2.77,  8.3 ,  7.77,  7.33,  6.21,  7.72,  8.98,  8.64,
        8.2 ,  3.93,  4.85,  4.85,  6.07,  8.98,  4.51, -0.05,  3.69,
        4.56,  0.58,  2.82, -4.95, -0.29,  7.86, -0.19, -2.14,  3.06,
        0.34, -4.32,  1.07])

In [58]:
def regress(Test_x,Train_x,Train_y,n):
    import scipy
    import numpy as np
    out=[]
    for _ in range(len(Test_x)):
        if _%100==0:
            print(_*100/len(Test_x)," % , Complete")
        out_current=[]
        for __ in range(len(Train_y[0])):   
            dist=[]
            val=[]
            for ___ in range(len(Train_y)):
                if Train_y[___][__]!=99.0:
                    Test_New=[]
                    Train_New=[]
                    for ____ in range(len(Test_x[0])):
                        if Test_x[_][____]==99.0 and Train_x[___][____]==99.0:
                            Test_New.append(10.0)
                            Train_New.append(-10.0)
                        elif Test_x[_][____]!=99.0 and Train_x[___][____]==99.0:
                            Test_New.append(Test_x[_][____])
                            if Test_x[_][____]<0:
                                Train_New.append(10.0)
                            else:
                                Train_New.append(-10.0)
                        elif Test_x[_][____]==99.0 and Train_x[___][____]!=99.0:
                            Train_New.append(Train_x[___][____])
                            if Train_x[___][____]<0:
                                Test_New.append(10.0)
                            else:
                                Test_New.append(-10.0)
                        else:
                            Test_New.append(Test_x[_][____])
                            Train_New.append(Train_x[___][____])
                    Test_New = np.array(Test_New[:n])
                    Train_New = np.array(Train_New[:n])
                    Distance = scipy.spatial.distance.euclidean(Test_New,Train_New)
                    dist.append(1/Distance)
                    val.append(Train_y[___][__])
            dist = np.array(dist)
            total = np.sum(dist)
            dist = dist/total
            val = np.array(val)
            prediction = dist*val
            final = np.sum(prediction)
            out_current.append(final)
        out_current = np.array(out_current)
        out.append(out_current)
    out = np.array(out)
    return out
                    
                    
            

In [60]:
out = regress(Test_x[:1],Train_x,Train_y,10)

0.0  % , Complete


In [61]:
out

array([[-2.00912513,  2.09732198,  0.98281595, -2.30749704, -1.18410006,
         1.80907622,  0.10335543,  1.34953637, -1.0429071 ,  1.01736053,
         1.03429175, -0.53375945,  1.20993897, -0.31691487,  0.21198878,
        -0.23834643,  1.42135821,  0.94042904,  2.18012749, -0.78044133,
         0.94887701,  0.34672702,  1.40505135,  0.29073561,  0.58720697,
         0.58957222,  0.74617654,  0.34594153, -0.3264413 ,  1.03739586]])

In [56]:
out

array([[-1.96449539,  2.15449997,  1.04825151, -2.2458837 , -1.11188821,
         1.8425136 ,  0.15509356,  1.42137219, -0.97756928,  1.08798092,
         1.0985013 , -0.4936451 ,  1.2592789 , -0.26577974,  0.30315912,
        -0.21390759,  1.46777686,  0.97089042,  2.19322839, -0.72433451,
         0.97768763,  0.37977701,  1.44504968,  0.30688768,  0.61488341,
         0.63918798,  0.79148865,  0.42513094, -0.2812577 ,  1.13082436]])

In [49]:
out

array([[-2.10512548,  2.06930722,  0.99155391, -2.36594337, -1.22631188,
         1.76495342,  0.04804021,  1.3452304 , -1.08205012,  1.0229564 ,
         1.0114038 , -0.63190727,  1.18124651, -0.40352451,  0.1812332 ,
        -0.33315702,  1.38791786,  0.87984017,  2.08842987, -0.86685641,
         0.892147  ,  0.27870989,  1.34642038,  0.21047969,  0.51821891,
         0.52230448,  0.65570397,  0.34180065, -0.39988605,  1.01542156]])

In [51]:
Test_y[0]

array([-5.  ,  2.77,  8.3 ,  7.77,  7.33,  6.21,  7.72,  8.98,  8.64,
        8.2 ,  3.93,  4.85,  4.85,  6.07,  8.98,  4.51, -0.05,  3.69,
        4.56,  0.58,  2.82, -4.95, -0.29,  7.86, -0.19, -2.14,  3.06,
        0.34, -4.32,  1.07])

In [53]:
Test_y[0]-out[0]

array([ -2.89487452e+00,   7.00692785e-01,   7.30844609e+00,
         1.01359434e+01,   8.55631188e+00,   4.44504658e+00,
         7.67195979e+00,   7.63476960e+00,   9.72205012e+00,
         7.17704360e+00,   2.91859620e+00,   5.48190727e+00,
         3.66875349e+00,   6.47352451e+00,   8.79876680e+00,
         4.84315702e+00,  -1.43791786e+00,   2.81015983e+00,
         2.47157013e+00,   1.44685641e+00,   1.92785300e+00,
        -5.22870989e+00,  -1.63642038e+00,   7.64952031e+00,
        -7.08218905e-01,  -2.66230448e+00,   2.40429603e+00,
        -1.80065169e-03,  -3.92011395e+00,   5.45784386e-02])

In [57]:
Test_y[0]-out[0]

array([ -3.03550461,   0.61550003,   7.25174849,  10.0158837 ,
         8.44188821,   4.3674864 ,   7.56490644,   7.55862781,
         9.61756928,   7.11201908,   2.8314987 ,   5.3436451 ,
         3.5907211 ,   6.33577974,   8.67684088,   4.72390759,
        -1.51777686,   2.71910958,   2.36677161,   1.30433451,
         1.84231237,  -5.32977701,  -1.73504968,   7.55311232,
        -0.80488341,  -2.77918798,   2.26851135,  -0.08513094,
        -4.0387423 ,  -0.06082436])

In [62]:
Test_y[0]-out[0]

array([ -2.99087487e+00,   6.72678024e-01,   7.31718405e+00,
         1.00774970e+01,   8.51410006e+00,   4.40092378e+00,
         7.61664457e+00,   7.63046363e+00,   9.68290710e+00,
         7.18263947e+00,   2.89570825e+00,   5.38375945e+00,
         3.64006103e+00,   6.38691487e+00,   8.76801122e+00,
         4.74834643e+00,  -1.47135821e+00,   2.74957096e+00,
         2.37987251e+00,   1.36044133e+00,   1.87112299e+00,
        -5.29672702e+00,  -1.69505135e+00,   7.56926439e+00,
        -7.77206969e-01,  -2.72957222e+00,   2.31382346e+00,
        -5.94152754e-03,  -3.99355870e+00,   3.26041355e-02])